### ISSUE TITLE
Support for user cookbook / chef-solo

### ISSUE THREAD

**Issue by cburyta** [hw-cookbooks/oh-my-zsh#3]
It would be good to be able to use this on a chef-solo setup. The search function only works on the chef-client / server setup.

**Comment by EugenMayer** [comment]
@cburyta are you sure? since this works pretty well with berkshelf and kitchen-test where you have no server. You know that you can create databags in your cookbook?

**Comment by cburyta** [comment]
@EugenMayer A lot has changed with chef-solo in the past 4 years. This might be invalid now.

**Comment by EugenMayer** [comment]
@cburyta excuse myself, i was not aware that an issue being open after 4 years .. but seems like that is a pretty dead project, regarding the pull requests and so on. Thanks for clarifiyin
